<div angular-lazy-load><div id=home-top-section><div id=main-slider><div class=items><img data-src=assets/img/slider/crystal-silver-chairs.jpg alt=3></div><div class=items><img data-src=assets/img/slider/outside-view.jpg alt=3></div></div><div class="booking-form-container container"><div id=main-booking-form class=style-2><h2>Book a <span>Facility</span></h2><form class="booking-form clearfix" action=#><div class="input-daterange clearfix"><div class="booking-fields col-xs-6 col-md-12"><input placeholder="Choose check in date" class="datepicker-fields check-in" type=text name=start id=chkIndate><i class="fa fa-calendar"></i></div><div class="booking-fields col-xs-6 col-md-12"><input placeholder="Choose check out date" class="datepicker-fields check-out" type=text name=end id=chkOutdate> <i class="fa fa-calendar"></i></div></div><div class="booking-fields col-xs-6 col-md-12" id=divToPutSelect><select name=facSelect id=SelectFacilities ng-selected=resp.facility><option>Facilities</option><option ng-repeat="resp in indexData" value={{resp.fid}}>{{resp.facility}}</option></select></div><div class=booking-button-container><a class="btn btn-default btn-block checkAvail" ng-click=CheckAvailabilty()>Check Availability</a></div><div id=response style="margin-top: 20px;"></div></form></div></div></div><div id=luxury-rooms><div class=heading-box><h2>Our <span>Facilities</span></h2><div class=subtitle>Best facilities at best prices</div></div><div class="room-container container" id=facilityDiv><div class=room-boxes dir-paginate="resp in indexData | itemsPerPage: 2" ng-class="{right: $index % 2 === 0}"><img src=http://paago.eventcalender.develop.cinfores.com/uploads/{{resp.image1}} alt={{resp.facility}} class=room-img><div class="room-details col-xs-6 col-md-4"><div class=title>{{resp.facility}}</div><div class=description>{{resp.fdesc}}</div><a class="btn btn-default" ui-sref="booking({facId: resp.fid, facName: resp.facility})" ng-click=showLoad()>Book Now</a></div><div class="price-container col-xs-6 col-md-8"><div class=price><span>&#8358; {{resp.costdays | number:0}}</span> only</div></div></div><div class=pagination-box style="margin-bottom: -80px;"><dir-pagination-controls></dir-pagination-controls></div></div></div><div class=heading-box><h2>Take a <span>Peek</span></h2></div><div ng-include="'views/gallery_view.php'"></div></div><script type=text/javascript src=assets/js/template.js></script><script>
    // Main Slider
    jQuery("#main-slider").owlCarousel({
        navigation : !1,
        singleItem : !0,
        addClassActive : !0,
        autoPlay : !0,
        mouseDrag : !1,
        touchDrag : !1,
    });
</script>
